apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}-varnish
  labels:
    app: {{ template "name" . }}-varnish
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "name" . }}-varnish
  minReplicas: {{ .Values.varnish.minReplicaCount }}
  maxReplicas: {{ .Values.varnish.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          kind: AverageUtilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        targetAverageValue: 1k